### ISSUE TITLE
console.kuzzle.io is not updated to the last version 

### ISSUE THREAD

**Issue by Tyki** [kuzzleio/kuzzle-console#422]
The documentation bring the user to http://console.kuzzle.io/#/data
This admin console looks not updated to the last version.

But the netlify looks up-to-date : http://kuzzle-backoffice.netlify.com/#/data

**Comment by Aschen** [comment]
Hi,

It seems that our CI does not deploy http://console.kuzzle.io when we release the admin console.  
We will investigate that issue shortly, thanks you for the report.

**Comment by alexandrebouthinon** [comment]
Hi, 
It should be fixed now.
